- hosts: all
  become: yes
  tasks:
    - name: create the 'cestmoi' user
      user: name=cestmoi append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'cestmoi' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: "cestmoi ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"

    - name: set up authorized keys for the cestmoi user
      authorized_key: user=cestmoi key="{{item}}"
      with_file:
        - ~/.ssh/digoc2.pub
