- hosts: master
  become: true
  become_user: cestmoi
  tasks:
    - name: run kubebench for workers
      shell: kubectl apply -f https://raw.githubusercontent.com/aquasecurity/kube-bench/master/job-node.yaml

    - pause: seconds=10

    - name: echo results for node tests
      shell: kubectl logs $(kubectl get pods | grep kube-bench-node | awk '{print $1}') | tee ~/node_result.txt

    - name: copy output of node test to local machine
      fetch:
        src: ~/node_result.txt
        dest: ./node_result.txt
        flat: yes

    - name: run kubebench for master
      shell: kubectl apply -f https://raw.githubusercontent.com/aquasecurity/kube-bench/master/job-master.yaml

    - pause: seconds=10

    - name: record results for master test
      shell: kubectl logs $(kubectl get pods | grep kube-bench-master | awk '{print $1}') | tee ~/master_result.txt

    - name: copy output of node test to local machine
      fetch:
        src: ~/master_result.txt
        dest: ./master_result.txt
        flat: yes

    - name: cleanup
      shell: rm ~/master_result.txt ~/node_result.txt
