- hosts: all
  become: yes
  tasks:
    - name: add docker respository
      shell: "dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo"

    - name: install containerd
      dnf:
        name: "https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm"
        state: present

    - name: install docker
      denf:
        name: "docker-ce"
        state: present

    - name: enable docker and ensure it is not masked
      systemd:
        name: docker
        enabled: yes
        masked: no

    - name: start Docker
      service:
        name: docker
        state: started

    - name: disable SELinux
      command: setenforce 0

    - name: disable SELinux on reboot
      selinux:
        state: disabled

    - name: fix iptables
      shell: modprobe br_netfilter

    - name: fix iptables v2
      shell: sysctl -p /etc/sysctl.conf

    - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
      sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: 1
        state: present

    - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present

    - name: add Kubernetes' YUM repository
      yum_repository:
        name: Kubernetes
        description: Kubernetes YUM repository
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        gpgcheck: yes

    - name: install kubelet
      yum:
        name: kubelet-1.14.0
        state: present
        update_cache: true

    - name: install kubeadm
      yum:
        name: kubeadm-1.14.0
        state: present

    - name: start kubelet
      service:
        name: kubelet
        enabled: yes
        state: started

- hosts: master
  become: yes
  tasks:
    - name: install kubectl
      yum:
        name: kubectl-1.14.0
        state: present
        allow_downgrade: yes
